### ISSUE TITLE
Add tracks integration for shipping zone instances

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#295]
We should track events for:

* [x] whenever a site adds a WooCommerce Connect service to a shipping zone -- #326
* [x] whenever a user saves the settings for a service (e.g. USPS instance settings) -- #320 
* [x] whenever a site removes a WooCommerce Connect service from a shipping zone -- #326
